### ISSUE TITLE
cli.PrivateANNQuery(keys) always returns 0

### ISSUE THREAD

**Issue by matsutakk** [sachaservan/private-ann#1]
Hi, from Japan. 

I have read your wonderful paper using DPF to retrieve similar data in a privacy-preserving way (two non-colluding servers and malicious setting).

I would like to employ this scheme, however, [cli.PrivateANNQuery(keys)](https://github.com/sachaservan/private-ann/blob/4a4fd93b1378c94132f83d9efa5e070516ea32d4/cmd/client/main.go#L82) always returns 0.

I have missed something important??

Thank you for your great work.

**Comment by matsutakk** [comment]
I also checked the situation using the training dataset as below, but candidate is always zero.
```go
cmd/client/main.go
	for i := 0; i < args.ExperimentNumTrials; i++ {
                ~~~~~~~~~~~~~~~~~

		var trainingData []*vec.Vec
		trainingData, _, _, _ = ann.ReadDataset("../datasets/mnist")
		for index, value := range trainingData {
			q := value

			keys := make([][]uint64, cli.SessionParams.NumTables)
			for i := range keys {
				// Returns numProbes values inserted into numPartition buckets
				// 0 is the value in slots without hashes
				// Here numPartitions = numProbes
				keys[i] = ann.ComputeProbes(cli.SessionParams.HashFunctions[i], q, cli.SessionParams.NumProbes, cli.SessionParams.NumProbes)
			}
			// Step 3: query the buckets using PIR
			log.Printf("[Client]: querying %v buckets in %v tables\n",
				cli.SessionParams.NumTables*cli.SessionParams.NumProbes,
				cli.SessionParams.NumTables)

			candidate := cli.PrivateANNQuery(keys)
			fmt.Printf("%v,%v", index, candidate)
			fmt.Println()
			queryTime := time.Since(start).Milliseconds()
			cli.Experiment.QueryClientMS = append(cli.Experiment.QueryClientMS, queryTime)
			log.Printf("[Client]: ANN query took %v seconds\n", time.Since(start).Seconds())
		}
		// Experiment completed
		log.Printf("[Client]: finished experiment trial %v of %v \n", i+1, args.ExperimentNumTrials)
	}
```

**Comment by matsutakk** [comment]
I fixed this by three changes

1. [this line](https://github.com/sachaservan/private-ann/blob/4a4fd93b1378c94132f83d9efa5e070516ea32d4/client/client.go#L144) should be changed to
```go
argsB.SecretShared = allQueriesB
```
2. [this part](https://github.com/sachaservan/private-ann/blob/4a4fd93b1378c94132f83d9efa5e070516ea32d4/pir/db.go#L146) should be 
```go
for i := 0; i < stop-start; i++ {
  bits[i] = field.FP(bitsRaw[i])
}
```

3.  The client should call hash.Precompute() somewhere, say, [this part](https://github.com/sachaservan/private-ann/blob/4a4fd93b1378c94132f83d9efa5e070516ea32d4/cmd/client/main.go#L48)
```go
cli.Experiment.QueryDownBandwidthBytes = make([]int64, 0)
hash.Precompute()
for i := 0; i < args.ExperimentNumTrials; i++ {
~~~~~~~
```

**Comment by sachaservan** [comment]
@matsutakk hey sorry I didn't have time to look at it until now.  Thanks for finding the bug and fixing it! 
I'll update the code shortly with your fix or if you want to create a pull request I can merge it.

**Comment by matsutakk** [comment]
Thank you for you reply!

I will create a pull request later.
